oltf_data_acq_node:
  ros__parameters:
    joint_name_to_test: "joint2"
    effort_command_topic: "/joint2_effort_controller/commands"

    initial_settle_duration: 2.0
    
    torque_sequence:
      - 160.0
      - 2.8
      - 120.0
      - 1.1
      - -190.0
      - 1.7
      - 180.0
      - 1.2
      - -190.0
      - 1.0

    final_settle_duration: 3.0 #s

    log_frequency: 50.0 #Hz
    log_file_path: "./test1.csv"